//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Table
    {
        public int Id { get; set; }
        public string Contract_period { get; set; }
        public string Start_date { get; set; }
        public string End_date { get; set; }
        public string Salary { get; set; }
    }
}
