//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Table
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public string Series { get; set; }
        public string Data { get; set; }
        public string CNP { get; set; }
        public string Job { get; set; }
    }
}
